### ISSUE TITLE
empty dir, get error on init about 'already exists in this directory'

### ISSUE THREAD

**Issue by meeech** [instacart/lore#113]
hi. trying:
```
lore init . --python-version=3.6.6
> INFO converting existing directory to a Lore App
> ERROR "." already exists in this directoy! Add --bare to avoid clobbering existing files.
```
This is an empty dir - is this the expected behaviour?

`lore version: system version: 0.6.14`

**Comment by montanalow** [comment]
That's a good point. I think it would be a good special case to handle as a feature improvement. Do you want to implement?

**Comment by meeech** [comment]
Sure!

**Comment by meeech** [comment]
@montanalow started on it - https://github.com/meeech/lore/tree/issue-113-init-empty-dir - any guidance re tests welcome, or should i not bother for this change (i was looking for relevant ones to expand on, but didn't see them)

**Comment by montanalow** [comment]
Resolved by @meeech
