### ISSUE TITLE
Docs failing

### ISSUE THREAD

**Issue by impredicative** [instacart/lore#81]

**Comment by montanalow** [comment]
@impredicative There is the beginning of a sphinx project in `docs/`, which is not much more than a failing stub at the moment. Contributions are welcome.

**Comment by ganesh-krishnan** [comment]
@impredicative This is open source software - people do this in their spare time. So please don't "expect" things. If it's useful to you, please use and share it. If not, I'm sure there are other projects that are looking for your critical comments. :)

**Comment by impredicative** [comment]
@ganesh-krishnan I am afraid that is just not true for this project. This is a corporate owned and maintained project. The bar for such projects is much higher. It is not an individual submission. I also refer you to https://www.infoworld.com/article/3268001/open-source-tools/open-source-isnt-the-community-you-think-it-is.html to understand what open source actually is.

IMHO, this project should be closed to the public and made private for a year or more until it can be made more mature for release.
